# Generated by Django 2.2 on 2021-01-29 13:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='created time')),
                ('name', models.CharField(max_length=50, verbose_name='course name')),
                ('desc', models.CharField(max_length=300, verbose_name='course description')),
                ('time_duration', models.IntegerField(default=0, verbose_name='course duration(minuites)')),
                ('degree', models.CharField(choices=[('cj', 'primary'), ('zj', 'medium'), ('gj', 'advanced')], max_length=10, verbose_name='difficulty')),
                ('students', models.IntegerField(default=0, verbose_name='number of students')),
                ('fav_num', models.IntegerField(default=0, verbose_name='number of collects')),
                ('category', models.CharField(default='backend development', max_length=20, verbose_name='course category')),
                ('tag', models.CharField(default='', max_length=20, verbose_name='course tags')),
                ('youneed_know', models.CharField(default='', max_length=300, verbose_name='course notice')),
                ('teacher_tell', models.CharField(default='', max_length=300, verbose_name="teacher's words")),
                ('detail', models.TextField(verbose_name='course detail')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='cover image')),
                ('tacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher')),
            ],
            options={
                'verbose_name': 'course',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='created time')),
                ('name', models.CharField(max_length=100, verbose_name='lesson name')),
                ('time_duration', models.IntegerField(default=0, verbose_name='learning duration')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'verbose_name': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='created time')),
                ('name', models.CharField(max_length=100, verbose_name='video name')),
                ('time_duration', models.IntegerField(default=0, verbose_name='time duration')),
                ('url', models.CharField(max_length=200, verbose_name='access address')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson')),
            ],
            options={
                'verbose_name': 'video',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='created time')),
                ('name', models.CharField(max_length=100, verbose_name='resource name')),
                ('file', models.FileField(max_length=200, upload_to='course/resourses/%Y/%m')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
