# Generated by Django 2.2 on 2021-01-29 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210129_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tacher',
            new_name='teacher',
        ),
    ]
