# Generated by Django 2.2 on 2021-02-01 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20210201_1559'),
        ('courses', '0003_auto_20210129_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='Course Organization'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(default='backend development', max_length=20, verbose_name='Course Category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('cj', 'primary'), ('zj', 'medium'), ('gj', 'advanced')], max_length=10, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.CharField(max_length=300, verbose_name='Course Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.TextField(verbose_name='Course Detail'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='Number of Collects'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='courses/%Y/%m', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.IntegerField(default=0, verbose_name='Student Number'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=20, verbose_name='Course Tag'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=300, verbose_name="Teacher's Words"),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_duration',
            field=models.IntegerField(default=0, verbose_name='Course Duration(minutes)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='youneed_know',
            field=models.CharField(default='', max_length=300, verbose_name='Course Notice'),
        ),
    ]
