# Generated by Django 2.2 on 2021-02-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210201_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_classical',
            field=models.BooleanField(default=False, verbose_name='if Top'),
        ),
    ]
