# Generated by Django 2.2 on 2021-02-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursetag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tag',
        ),
    ]
