# Generated by Django 2.2 on 2021-01-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20210129_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecomment',
            old_name='add_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='userconsult',
            old_name='add_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='usercourse',
            old_name='add_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='userfavorite',
            old_name='add_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='usermessage',
            old_name='add_time',
            new_name='created_time',
        ),
    ]
