# Generated by Django 2.2 on 2021-02-03 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20210129_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='created time')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(max_length=200, upload_to='banner/%Y/%m', verbose_name='Carousel Figure')),
                ('url', models.URLField(verbose_name='access address')),
                ('index', models.IntegerField(default=0, verbose_name='order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
