# Generated by Django 2.2 on 2021-01-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='add_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='courseorg',
            old_name='add_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='add_time',
            new_name='created_time',
        ),
    ]
