# Generated by Django 2.2 on 2021-02-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20210201_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='is_auth',
            field=models.BooleanField(default=False, verbose_name='if authenticated'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='is_golden',
            field=models.BooleanField(default=False, verbose_name='if golden'),
        ),
    ]
