# Generated by Django 2.2 on 2021-02-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20210201_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
    ]
